// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import ProgressBarController from "./progress_bar_controller"
application.register("progress-bar", ProgressBarController)

import RangeSliderController from "./range_slider_controller"
application.register("range-slider", RangeSliderController)

import SearchSalesController from "./search_sales_controller"
application.register("search-sales", SearchSalesController)
